# Generated by Django 2.2.27 on 2022-05-30 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_unifi_portal', '0004_auto_20170613_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Cadastrado em'),
            preserve_default=False,
        ),
    ]
